### ISSUE TITLE
Syntax hightlighting

### ISSUE THREAD

**Issue by marcel3032** [trojsten/ksp-school#20]
Aktuálne je hightlightovaná syntax aj taká, ktorá nepatrí pythonu, a potom to teda hightlightuje napríklad aj `do` v komentároch, nerozoznáva to komentáre a také
![Screenshot from 2022-02-02 11-01-52](https://user-images.githubusercontent.com/18122517/152132830-1930b588-960a-4053-b664-3909e5f6eb54.png)

**Comment by david58** [comment]
ak dobre pozerám je to markdown extension CodeHilite, ten autodetect jazyka väčšinou nefunguje na krátkych snippetoch, ale malo by fungovať keď dáš na prvý riadok niečo takéto `:::python` :thinking:

**Comment by marcel3032** [comment]
jo, funguje, vďaka :)
