### ISSUE TITLE
Náhľad pre vedúcich

### ISSUE THREAD

**Issue by david58** [trojsten/ksp-school#29]
Vrámci LŠ má zmysel mať niečo ako výsledkovku kde vidíš progress účastníkov a dá sa odhaliť či sa niekto na niečom zasekol. School začína na nule, takže sa dá na začiatok spraviť nejaká jedna spoločná tabuľka kde budú riešitelia krát texty/úlohy a vidíš kto čo prešiel, neskôr treba filtrovať aktuálnych účastníkov a možno odlíšiť staré vyriešené úlohy

Na disksiu je, či nejakú formu výsledkovky alebo pozerania iných submitov dať účastníkom. Liaheň mala pozeranie všetkých OK submitov po vyriešení úlohy, to podla mňa stačí nahradiť vzorákmi, testovač mal výsledkovku kde sa deti radi porovnávali, ale možno to nie je až taký plus pre účely school a LŠ

**Comment by marcel3032** [comment]
Jo, náhľad pre vedúcich je v todoliste, ideálne to chceme do lš, uvidíme či stihneme 😁

**Comment by gardenerik** [comment]
základné triedy s výsledkovkami prišli v #36
